### ISSUE TITLE
Question about node:crypto

### ISSUE THREAD

**Issue by rwv** [bruceharrison1984/bcrypt-edge#10]
README says that this project is mainly for web workers and Cloudflare workers. Why `node:crypto` is imported in v0.0.5 instead of WebCrypto?

See also https://developers.cloudflare.com/workers/runtime-apis/web-crypto/#methods

**Comment by bruceharrison1984** [comment]
I wrote this specifically for use on Cloudflare, which aliases `node:crypto`.

https://developers.cloudflare.com/workers/runtime-apis/nodejs/crypto/

However, I'm now uncertain if the `node:crypto` shim provided by Cloudflare is the same implementation as is provided by WebCrypto. I presumed it was, but you raise a good point.

**Comment by rwv** [comment]
node:crypto will not work in Web Worker in browser environment. Also I don't think that cloudflare alias nods:crypto however `crypto` is `globalThis.crypto` which is WebCrypto.

**Comment by bruceharrison1984** [comment]
`node:crypto` works fine in CF as long as you've enabled node compatibility.

However, it's not necessary due to WebCrypro being available as a global. I'll cut a new version and revert this back to what it was.
